import { atom } from "recoil";

export const aboutMeAtom = atom({
  key: "aboutMeAtom",
  default: `👋 Hii, I'm .... , a Fullstack-engineer from India.
  💻 I'm currently Working on ....
  👯 I'm looking to collaborate on ....
  🤝 I'm looking for help with ....
  🌱 I'm currently learning ....
  💬 Ask me about ....
  `,
});
